package ms.luna.biz.dao.model;

import java.io.Serializable;
import java.util.Date;

public class MsPoiField implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.field_name
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private String fieldName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.field_show_name
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private String fieldShowName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.field_alias
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private String fieldAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.display_order
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private Integer displayOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.field_type
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private Integer fieldType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.field_size
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private Integer fieldSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.placeholder
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private String placeholder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.field_tips_for_templete
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private String fieldTipsForTemplete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.extension_attrs
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private String extensionAttrs;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.field_introduction
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private String fieldIntroduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.regist_hhmmss
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private Date registHhmmss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.up_hhmmss
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private Date upHhmmss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_poi_field.updated_by_unique_id
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private String updatedByUniqueId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.field_name
     *
     * @return the value of ms_poi_field.field_name
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public String getFieldName() {
        return fieldName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.field_name
     *
     * @param fieldName the value for ms_poi_field.field_name
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName == null ? null : fieldName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.field_show_name
     *
     * @return the value of ms_poi_field.field_show_name
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public String getFieldShowName() {
        return fieldShowName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.field_show_name
     *
     * @param fieldShowName the value for ms_poi_field.field_show_name
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setFieldShowName(String fieldShowName) {
        this.fieldShowName = fieldShowName == null ? null : fieldShowName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.field_alias
     *
     * @return the value of ms_poi_field.field_alias
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public String getFieldAlias() {
        return fieldAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.field_alias
     *
     * @param fieldAlias the value for ms_poi_field.field_alias
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setFieldAlias(String fieldAlias) {
        this.fieldAlias = fieldAlias == null ? null : fieldAlias.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.display_order
     *
     * @return the value of ms_poi_field.display_order
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public Integer getDisplayOrder() {
        return displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.display_order
     *
     * @param displayOrder the value for ms_poi_field.display_order
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.field_type
     *
     * @return the value of ms_poi_field.field_type
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public Integer getFieldType() {
        return fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.field_type
     *
     * @param fieldType the value for ms_poi_field.field_type
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setFieldType(Integer fieldType) {
        this.fieldType = fieldType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.field_size
     *
     * @return the value of ms_poi_field.field_size
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public Integer getFieldSize() {
        return fieldSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.field_size
     *
     * @param fieldSize the value for ms_poi_field.field_size
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setFieldSize(Integer fieldSize) {
        this.fieldSize = fieldSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.placeholder
     *
     * @return the value of ms_poi_field.placeholder
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public String getPlaceholder() {
        return placeholder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.placeholder
     *
     * @param placeholder the value for ms_poi_field.placeholder
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setPlaceholder(String placeholder) {
        this.placeholder = placeholder == null ? null : placeholder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.field_tips_for_templete
     *
     * @return the value of ms_poi_field.field_tips_for_templete
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public String getFieldTipsForTemplete() {
        return fieldTipsForTemplete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.field_tips_for_templete
     *
     * @param fieldTipsForTemplete the value for ms_poi_field.field_tips_for_templete
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setFieldTipsForTemplete(String fieldTipsForTemplete) {
        this.fieldTipsForTemplete = fieldTipsForTemplete == null ? null : fieldTipsForTemplete.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.extension_attrs
     *
     * @return the value of ms_poi_field.extension_attrs
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public String getExtensionAttrs() {
        return extensionAttrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.extension_attrs
     *
     * @param extensionAttrs the value for ms_poi_field.extension_attrs
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setExtensionAttrs(String extensionAttrs) {
        this.extensionAttrs = extensionAttrs == null ? null : extensionAttrs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.field_introduction
     *
     * @return the value of ms_poi_field.field_introduction
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public String getFieldIntroduction() {
        return fieldIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.field_introduction
     *
     * @param fieldIntroduction the value for ms_poi_field.field_introduction
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setFieldIntroduction(String fieldIntroduction) {
        this.fieldIntroduction = fieldIntroduction == null ? null : fieldIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.regist_hhmmss
     *
     * @return the value of ms_poi_field.regist_hhmmss
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public Date getRegistHhmmss() {
        return registHhmmss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.regist_hhmmss
     *
     * @param registHhmmss the value for ms_poi_field.regist_hhmmss
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setRegistHhmmss(Date registHhmmss) {
        this.registHhmmss = registHhmmss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.up_hhmmss
     *
     * @return the value of ms_poi_field.up_hhmmss
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public Date getUpHhmmss() {
        return upHhmmss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.up_hhmmss
     *
     * @param upHhmmss the value for ms_poi_field.up_hhmmss
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setUpHhmmss(Date upHhmmss) {
        this.upHhmmss = upHhmmss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_poi_field.updated_by_unique_id
     *
     * @return the value of ms_poi_field.updated_by_unique_id
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public String getUpdatedByUniqueId() {
        return updatedByUniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_poi_field.updated_by_unique_id
     *
     * @param updatedByUniqueId the value for ms_poi_field.updated_by_unique_id
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void setUpdatedByUniqueId(String updatedByUniqueId) {
        this.updatedByUniqueId = updatedByUniqueId == null ? null : updatedByUniqueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsPoiField other = (MsPoiField) that;
        return (this.getFieldName() == null ? other.getFieldName() == null : this.getFieldName().equals(other.getFieldName()))
            && (this.getFieldShowName() == null ? other.getFieldShowName() == null : this.getFieldShowName().equals(other.getFieldShowName()))
            && (this.getFieldAlias() == null ? other.getFieldAlias() == null : this.getFieldAlias().equals(other.getFieldAlias()))
            && (this.getDisplayOrder() == null ? other.getDisplayOrder() == null : this.getDisplayOrder().equals(other.getDisplayOrder()))
            && (this.getFieldType() == null ? other.getFieldType() == null : this.getFieldType().equals(other.getFieldType()))
            && (this.getFieldSize() == null ? other.getFieldSize() == null : this.getFieldSize().equals(other.getFieldSize()))
            && (this.getPlaceholder() == null ? other.getPlaceholder() == null : this.getPlaceholder().equals(other.getPlaceholder()))
            && (this.getFieldTipsForTemplete() == null ? other.getFieldTipsForTemplete() == null : this.getFieldTipsForTemplete().equals(other.getFieldTipsForTemplete()))
            && (this.getExtensionAttrs() == null ? other.getExtensionAttrs() == null : this.getExtensionAttrs().equals(other.getExtensionAttrs()))
            && (this.getFieldIntroduction() == null ? other.getFieldIntroduction() == null : this.getFieldIntroduction().equals(other.getFieldIntroduction()))
            && (this.getRegistHhmmss() == null ? other.getRegistHhmmss() == null : this.getRegistHhmmss().equals(other.getRegistHhmmss()))
            && (this.getUpHhmmss() == null ? other.getUpHhmmss() == null : this.getUpHhmmss().equals(other.getUpHhmmss()))
            && (this.getUpdatedByUniqueId() == null ? other.getUpdatedByUniqueId() == null : this.getUpdatedByUniqueId().equals(other.getUpdatedByUniqueId()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getFieldName() == null) ? 0 : getFieldName().hashCode());
        result = prime * result + ((getFieldShowName() == null) ? 0 : getFieldShowName().hashCode());
        result = prime * result + ((getFieldAlias() == null) ? 0 : getFieldAlias().hashCode());
        result = prime * result + ((getDisplayOrder() == null) ? 0 : getDisplayOrder().hashCode());
        result = prime * result + ((getFieldType() == null) ? 0 : getFieldType().hashCode());
        result = prime * result + ((getFieldSize() == null) ? 0 : getFieldSize().hashCode());
        result = prime * result + ((getPlaceholder() == null) ? 0 : getPlaceholder().hashCode());
        result = prime * result + ((getFieldTipsForTemplete() == null) ? 0 : getFieldTipsForTemplete().hashCode());
        result = prime * result + ((getExtensionAttrs() == null) ? 0 : getExtensionAttrs().hashCode());
        result = prime * result + ((getFieldIntroduction() == null) ? 0 : getFieldIntroduction().hashCode());
        result = prime * result + ((getRegistHhmmss() == null) ? 0 : getRegistHhmmss().hashCode());
        result = prime * result + ((getUpHhmmss() == null) ? 0 : getUpHhmmss().hashCode());
        result = prime * result + ((getUpdatedByUniqueId() == null) ? 0 : getUpdatedByUniqueId().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "MsPoiField [fieldName=" + fieldName + ",fieldShowName=" + fieldShowName + ",fieldAlias=" + fieldAlias + ",displayOrder=" + displayOrder + ",fieldType=" + fieldType + ",fieldSize=" + fieldSize + ",placeholder=" + placeholder + ",fieldTipsForTemplete=" + fieldTipsForTemplete + ",extensionAttrs=" + extensionAttrs + ",fieldIntroduction=" + fieldIntroduction + ",registHhmmss=" + registHhmmss + ",upHhmmss=" + upHhmmss + ",updatedByUniqueId=" + updatedByUniqueId + "]";
    }
}