package ms.luna.biz.dao.model;

import java.io.Serializable;

public class MsShowPageShare implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_show_page_share.id
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_show_page_share.business_id
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    private Integer businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_show_page_share.title
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_show_page_share.description
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_show_page_share.pic
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    private String pic;

    /**
     * This field was generated by Mark.
     *  ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_show_page_share.id
     *
     * @return the value of ms_show_page_share.id
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_show_page_share.id
     *
     * @param id the value for ms_show_page_share.id
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_show_page_share.business_id
     *
     * @return the value of ms_show_page_share.business_id
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_show_page_share.business_id
     *
     * @param businessId the value for ms_show_page_share.business_id
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_show_page_share.title
     *
     * @return the value of ms_show_page_share.title
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_show_page_share.title
     *
     * @param title the value for ms_show_page_share.title
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_show_page_share.description
     *
     * @return the value of ms_show_page_share.description
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_show_page_share.description
     *
     * @param description the value for ms_show_page_share.description
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_show_page_share.pic
     *
     * @return the value of ms_show_page_share.pic
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public String getPic() {
        return pic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_show_page_share.pic
     *
     * @param pic the value for ms_show_page_share.pic
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public void setPic(String pic) {
        this.pic = pic == null ? null : pic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsShowPageShare other = (MsShowPageShare) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getPic() == null ? other.getPic() == null : this.getPic().equals(other.getPic()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getPic() == null) ? 0 : getPic().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "MsShowPageShare [id=" + id + ",businessId=" + businessId + ",title=" + title + ",description=" + description + ",pic=" + pic + "]";
    }
}