package ms.luna.biz.dao;

import java.util.List;
import ms.biz.common.MsBaseDAO;
import ms.luna.biz.dao.model.MsPoiField;
import ms.luna.biz.dao.model.MsPoiFieldCriteria;

public abstract class MsPoiFieldDAOBaseImpl extends MsBaseDAO implements MsPoiFieldDAOBase {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public MsPoiFieldDAOBaseImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public int countByCriteria(MsPoiFieldCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ms_poi_field.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public int deleteByCriteria(MsPoiFieldCriteria example) {
        int rows = getSqlMapClientTemplate().delete("ms_poi_field.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void insert(MsPoiField record) {
        getSqlMapClientTemplate().insert("ms_poi_field.insert", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public void insertSelective(MsPoiField record) {
        getSqlMapClientTemplate().insert("ms_poi_field.insertSelective", record);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<MsPoiField> selectByCriteria(MsPoiFieldCriteria example) {
        List<MsPoiField> list = getSqlMapClientTemplate().queryForList("ms_poi_field.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public int updateByCriteriaSelective(MsPoiField record, MsPoiFieldCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ms_poi_field.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    public int updateByCriteria(MsPoiField record, MsPoiFieldCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ms_poi_field.updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    protected static class UpdateByExampleParms extends MsPoiFieldCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, MsPoiFieldCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}