package ms.luna.biz.dao;

import java.util.List;
import ms.luna.biz.dao.model.MsPoiField;
import ms.luna.biz.dao.model.MsPoiFieldCriteria;

public interface MsPoiFieldDAOBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    int countByCriteria(MsPoiFieldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    int deleteByCriteria(MsPoiFieldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    void insert(MsPoiField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    void insertSelective(MsPoiField record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    List<MsPoiField> selectByCriteria(MsPoiFieldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    int updateByCriteriaSelective(MsPoiField record, MsPoiFieldCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_poi_field
     *
     * @mbggenerated Tue Jul 05 16:58:03 CST 2016
     */
    int updateByCriteria(MsPoiField record, MsPoiFieldCriteria example);
}