package ms.biz.common.dao;

import java.util.List;
import ms.biz.common.MsBaseDAO;
import ms.biz.common.dao.model.MsShowPageShare;
import ms.biz.common.dao.model.MsShowPageShareCriteria;

public abstract class MsShowPageShareDAOBaseImpl extends MsBaseDAO implements MsShowPageShareDAOBase {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public MsShowPageShareDAOBaseImpl() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public int countByCriteria(MsShowPageShareCriteria example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("ms_show_page_share.countByExample", example);
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public int deleteByCriteria(MsShowPageShareCriteria example) {
        int rows = getSqlMapClientTemplate().delete("ms_show_page_share.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public int deleteByPrimaryKey(Integer id) {
        MsShowPageShare _key = new MsShowPageShare();
        _key.setId(id);
        int rows = getSqlMapClientTemplate().delete("ms_show_page_share.deleteByPrimaryKey", _key);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public Integer insert(MsShowPageShare record) {
        Object newKey = getSqlMapClientTemplate().insert("ms_show_page_share.insert", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public Integer insertSelective(MsShowPageShare record) {
        Object newKey = getSqlMapClientTemplate().insert("ms_show_page_share.insertSelective", record);
        return (Integer) newKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    @SuppressWarnings("unchecked")
    public List<MsShowPageShare> selectByCriteria(MsShowPageShareCriteria example) {
        List<MsShowPageShare> list = getSqlMapClientTemplate().queryForList("ms_show_page_share.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public MsShowPageShare selectByPrimaryKey(Integer id) {
        MsShowPageShare _key = new MsShowPageShare();
        _key.setId(id);
        MsShowPageShare record = (MsShowPageShare) getSqlMapClientTemplate().queryForObject("ms_show_page_share.selectByPrimaryKey", _key);
        return record;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public int updateByCriteriaSelective(MsShowPageShare record, MsShowPageShareCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ms_show_page_share.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public int updateByCriteria(MsShowPageShare record, MsShowPageShareCriteria example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("ms_show_page_share.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public int updateByPrimaryKeySelective(MsShowPageShare record) {
        int rows = getSqlMapClientTemplate().update("ms_show_page_share.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    public int updateByPrimaryKey(MsShowPageShare record) {
        int rows = getSqlMapClientTemplate().update("ms_show_page_share.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ms_show_page_share
     *
     * @mbggenerated Mon Jul 11 11:58:24 CST 2016
     */
    protected static class UpdateByExampleParms extends MsShowPageShareCriteria {
        private Object record;

        public UpdateByExampleParms(Object record, MsShowPageShareCriteria example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}