create table room_basic_info (
  id int(11) AUTO_INCREMENT comment '房间id',
  name VARCHAR(64) NOT NULL comment '房间名称',
  merchant_id VARCHAR(32) NOT NULL COMMENT '商户id',
  cate_id INT NOT NULL COMMENT '商品类别',
  start_time DATETIME NOT NULL COMMENT '开始时间',
  end_time DATETIME NOT NULL COMMENT '结束时间',
  workday_price DOUBLE NOT NULL COMMENT '平日价格',
  weekend_price DOUBLE NOT NULL COMMENT '周末价格',
  count int NOT NULL DEFAULT 0 COMMENT '库存量',
  area double NOT NULL COMMENT '总面积',
  floor int NOT NULL COMMENT '楼层',
  persons int NOT NULL COMMENT '人数',
  decoration int NOT NULL COMMENT '装修特点',
  landscape int NOT NULL COMMENT '景观特点',
  breakfast TINYINT NOT NULL DEFAULT 0 COMMENT '是否含早餐, 0:不含,1:含',
  room_num int NOT NULL DEFAULT 1 COMMENT '卧室数目',
  bed_info TEXT NOT NULL COMMENT '床型',
  basic_equip VARCHAR(32) NOT NULL COMMENT '基础设施',
  bedroom_equip VARCHAR(32) NOT NULL COMMENT '卧室',
  bath_equip VARCHAR(32) NOT NULL COMMENT '卫浴',
  cook_equip VARCHAR(32) NOT NULL COMMENT '餐厨',
  entertainment_equip VARCHAR(32) NOT NULL COMMENT '娱乐',
  pic_type int NOT NULL COMMENT '素材类型: 0:全景,1:平面图,2:无',
  pic_info TEXT COMMENT '图片内容',
  is_online TINYINT DEFAULT 0 COMMENT '是否上架',
  is_del TINYINT DEFAULT 0 COMMENT '是否删除',
  publish_time TIMESTAMP NULL DEFAULT NULL COMMENT '上架时间',
  create_time TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  update_time TIMESTAMP NOT NULL DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE (merchant_id, name),
  key(update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房间基础信息表';

create table room_other_info(
  room_id int(11) NOT NULL COMMENT '房间id',
  day DATETIME NOT NULL COMMENT '日期',
  is_special TINYINT NOT NULL DEFAULT 0 COMMENT '是否单独设置,避免被批量更新',
  count INT NOT NULL COMMENT '剩余数量',
  price DOUBLE NOT NULL COMMENT '价格',
  create_time TIMESTAMP NULL DEFAULT NULL COMMENT '创建时间',
  update_time TIMESTAMP NOT NULL DEFAULT current_timestamp ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (room_id, day),
  key(day),
  KEY(update_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='房间动态信息表';