ALTER table ms_article change COLUMN `abstract_content` `abstract_content` text NOT NULL COMMENT '摘要';
insert into ms_poi_field (field_name, field_show_name, display_order, field_type, field_size, placeholder, field_tips_for_templete, extension_attrs, field_introduction) values ("share_desc","分享摘要",3, 4, 20480, null, null, null, "用于针对单个POI点的分享介绍");
insert into  ms_r_tag_field (tag_id, field_name) values (1, "share_desc");
alter table ms_poi_field add column field_alias varchar(64) comment 'API对外暴露名称' after field_show_name;
update ms_poi_field set field_alias = "poi_name" where field_name = "long_title";
update ms_poi_field set field_alias = "other_name" where field_name = "short_title";
update ms_poi_field set field_alias = "category" where field_name = "tags";
update ms_poi_field set field_alias = "lnglat" where field_name = "lnglat";
update ms_poi_field set field_alias = "brief_introduction" where field_name = "brief_introduction";
update ms_poi_field set field_alias = "thumbnail" where field_name = "thumbnail";
update ms_poi_field set field_alias = "thumbnail_1_1" where field_name = "thumbnail_1_1";
update ms_poi_field set field_alias = "thumbnail_16_9" where field_name = "thumbnail_16_9";
update ms_poi_field set field_alias = "scene_type" where field_name = "scene_type";
update ms_poi_field set field_alias = "hotel_type" where field_name = "type";
update ms_poi_field set field_alias = "audio" where field_name = "audio";
update ms_poi_field set field_alias = "video" where field_name = "video";
update ms_poi_field set field_alias = "ticket_price" where field_name = "admission_ticket_price";
update ms_poi_field set field_alias = "opening_hours" where field_name = "opening_hours";
update ms_poi_field set field_alias = "price" where field_name = "price";
update ms_poi_field set field_alias = "number_of_rooms" where field_name = "number_of_rooms";
update ms_poi_field set field_alias = "facilities" where field_name = "including_facilities";
update ms_poi_field set field_alias = "opening_times" where field_name = "opening_times";
update ms_poi_field set field_alias = "last_decoration_time" where field_name = "last_decoration_time";
update ms_poi_field set field_alias = "business_hours" where field_name = "business_hours";
update ms_poi_field set field_alias = "zone_id" where field_name = "zone_id";
update ms_poi_field set field_alias = "detail_address" where field_name = "detail_address";
update ms_poi_field set field_alias = "area" where field_name = "merger_name";
update ms_poi_field set field_alias = "panorama_id" where field_name = "panorama";
update ms_poi_field set field_alias = "panorama_type" where field_name = "panorama_type";
update ms_poi_field set field_alias = "boundary" where field_name = "boundary";
update ms_poi_field set field_alias = "pay_method" where field_name = "pay_method";
update ms_poi_field set field_alias = "group" where field_name = "owned_group";
update ms_poi_field set field_alias = "sub_brand" where field_name = "sub_brand";
update ms_poi_field set field_alias = "share_desc" where field_name = "share_desc";
update ms_poi_field set field_alias = "contact_phone" where field_name = "contact_phone";
