package ms.luna.biz.dao.model;

import java.io.Serializable;
import java.util.Date;

public class MsRoute implements Serializable {
    /**
     * Database Column Remarks:
     *   线路id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   线路名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.name
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private String name;

    /**
     * Database Column Remarks:
     *   所属业务id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.business_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private Integer businessId;

    /**
     * Database Column Remarks:
     *   线路介绍
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.description
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private String description;

    /**
     * Database Column Remarks:
     *   体力消耗值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.cost_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private Integer costId;

    /**
     * Database Column Remarks:
     *   封面图
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.cover
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private String cover;

    /**
     * Database Column Remarks:
     *   创建人id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.unique_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private String uniqueId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.regist_hhmmss
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private Date registHhmmss;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ms_route.up_hhmmss
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private Date upHhmmss;

    /**
     * This field was generated by Mark.
     *  ms_route
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.id
     *
     * @return the value of ms_route.id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.id
     *
     * @param id the value for ms_route.id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.name
     *
     * @return the value of ms_route.name
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.name
     *
     * @param name the value for ms_route.name
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.business_id
     *
     * @return the value of ms_route.business_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public Integer getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.business_id
     *
     * @param businessId the value for ms_route.business_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setBusinessId(Integer businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.description
     *
     * @return the value of ms_route.description
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.description
     *
     * @param description the value for ms_route.description
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.cost_id
     *
     * @return the value of ms_route.cost_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public Integer getCostId() {
        return costId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.cost_id
     *
     * @param costId the value for ms_route.cost_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setCostId(Integer costId) {
        this.costId = costId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.cover
     *
     * @return the value of ms_route.cover
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public String getCover() {
        return cover;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.cover
     *
     * @param cover the value for ms_route.cover
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setCover(String cover) {
        this.cover = cover == null ? null : cover.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.unique_id
     *
     * @return the value of ms_route.unique_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public String getUniqueId() {
        return uniqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.unique_id
     *
     * @param uniqueId the value for ms_route.unique_id
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setUniqueId(String uniqueId) {
        this.uniqueId = uniqueId == null ? null : uniqueId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.regist_hhmmss
     *
     * @return the value of ms_route.regist_hhmmss
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public Date getRegistHhmmss() {
        return registHhmmss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.regist_hhmmss
     *
     * @param registHhmmss the value for ms_route.regist_hhmmss
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setRegistHhmmss(Date registHhmmss) {
        this.registHhmmss = registHhmmss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ms_route.up_hhmmss
     *
     * @return the value of ms_route.up_hhmmss
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public Date getUpHhmmss() {
        return upHhmmss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ms_route.up_hhmmss
     *
     * @param upHhmmss the value for ms_route.up_hhmmss
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    public void setUpHhmmss(Date upHhmmss) {
        this.upHhmmss = upHhmmss;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_route
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        MsRoute other = (MsRoute) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getBusinessId() == null ? other.getBusinessId() == null : this.getBusinessId().equals(other.getBusinessId()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getCostId() == null ? other.getCostId() == null : this.getCostId().equals(other.getCostId()))
            && (this.getCover() == null ? other.getCover() == null : this.getCover().equals(other.getCover()))
            && (this.getUniqueId() == null ? other.getUniqueId() == null : this.getUniqueId().equals(other.getUniqueId()))
            && (this.getRegistHhmmss() == null ? other.getRegistHhmmss() == null : this.getRegistHhmmss().equals(other.getRegistHhmmss()))
            && (this.getUpHhmmss() == null ? other.getUpHhmmss() == null : this.getUpHhmmss().equals(other.getUpHhmmss()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_route
     *
     * @mbggenerated Thu Jul 14 19:55:57 CST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getBusinessId() == null) ? 0 : getBusinessId().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getCostId() == null) ? 0 : getCostId().hashCode());
        result = prime * result + ((getCover() == null) ? 0 : getCover().hashCode());
        result = prime * result + ((getUniqueId() == null) ? 0 : getUniqueId().hashCode());
        result = prime * result + ((getRegistHhmmss() == null) ? 0 : getRegistHhmmss().hashCode());
        result = prime * result + ((getUpHhmmss() == null) ? 0 : getUpHhmmss().hashCode());
        return result;
    }

    @Override
    public String toString() {
        return "MsRoute [id=" + id + ",name=" + name + ",businessId=" + businessId + ",description=" + description + ",costId=" + costId + ",cover=" + cover + ",uniqueId=" + uniqueId + ",registHhmmss=" + registHhmmss + ",upHhmmss=" + upHhmmss + "]";
    }
}