//微景展
$(function(){
	var $overlay = $("#pop-overlay");//模态层，有效缓存变量
    //	新建微景展按钮
    $("#new-built").click(function () {
        addCata();
    });
    //    修改
    $("#list-page").on('click','a.modify',function(){
        modify();
    });
    //创建
    $("#setup").click(function(){
        createItem();
    });
    //编辑页面确定按钮
    $("#modify-confirm").click(function(){
        modifyItem();
    });
  //取消
    $("button.btn-clc").click(function(){
        $overlay.css("display","none");
        $("div.pop").css("display","none")
    });
   //中文名称实时校验
    $("#txt-name").blur(function(){
        verifyName();
    });
    //英文名称实时校验
    $("#txt-short").blur(function(){
        verifyAbbr();
    });
    //修改中文名称实时校验
    $("#txt-name-modify").blur(function(){
        modifyName();
    });
    //修改英文名称实时校验
    $("#txt-short-modify").blur(function(){
        modifyAbbr();
    });
    //删除
    $("#list-page").on('click','a.delete',function(){
        delCata(event);
    });
    //保存功能
    $("#btn-save").click(function(){
        save();
    });
    //    二维码预览
    $("#QR-code").click(function(){
        previewQR();
    });
    $("#QR-clc").click(function(){
    	$("#QR-show").css("display","none");
    })
    //页面级属性设计，需要与后台进行交互
    $("#btn-set").click(function(){
        setUp();
    });
    /*页面级属性设置缩略图删除功能*/
    $("#wj-page-clc").click(function(){
    	$("#wj-page").remove();
    })
    /*页面级属性设置，分享缩略图删除功能*/
    $("#wj-share-clc").click(function(){
    	$("#wj-share").remove();
    })
  // 确认页面级属性设置,此时存在数据发送
    $("#page-property").click(function(){
    	var params = {
    			app_id:$("#wj_app_id").val(),
    			app_name:$("#wj-page-title").val(),
    			app_note:$("#wj-page-description").val(),
    			app_thumb:$("#wj-page").attr("src"),

    			share_info_pic:$("#wj-share").attr("src"),
    			share_info_title:$("#wj-share-title").val(),
    			share_info_des:$("#wj-share-description").val()
    	};
    	$.ajax({
    		url: host + "/app.do?method=saveSettingOfApp",
	        type: 'POST',
	        async: false,
	        data: params,
	        dataType:"json",
	        success: function (returndata) {
	        	if ("0" == returndata.code) {
	        		alert("微景展设置保存成功!");
	        		$overlay.css("display","none");
		            $("#pop-set").css("display","none");
	        	} else {
	        		alert(returndata.msg);
	        		return;
	        	}
	        },
	        error: function (returndata) {
	            alert("请求失败");
	        }
	    });
    });

  //拖拽变换页面的顺序
    $('#list-page').droppable({
        activeClass: 'active',
        hoverClass: 'hover',
        accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
        drop: function (e, ui) {
            var $el = $('<li class="drop-item">' + ui.draggable.html() + '</li>');
            $(this).append($el);
        }
    }).sortable({
        items: '.drop-item',
        sort: function() {
            $( this ).removeClass( "active" );
        }
    });
    
    
  //弹出新增窗口
    function addCata(){
    	$("#txt-name").val('');
    	$("#txt-short").val('');

        $overlay.css("display","block");
        var $pop_window = $("#pop-add");
        var h = $pop_window.height();
        var w = $pop_window.width();
        var $height = $(window).height();
        var $width = $(window).width();
        $pop_window.css({
            "display":"block",
            "top":($height-h)/2,
            "left":($width-w)/2
        });
    }
    //编辑窗口
    function modify(){
        $overlay.css("display","block");
        var $pop_window = $("#pop-edit");
        var h = $pop_window.height();
        var w = $pop_window.width();
        var $height = $(window).height();
        var $width = $(window).width();
        $pop_window.css({
            "display":"block",
            "top":($height-h)/2,
            "left":($width-w)/2
        });
    }
    //+新建页面上的【确定】按钮
    function createItem(){
        var flag_name = true,
        	flag_short = true,
        	$txtName = $("#txt-name").val();
        if($txtName.length == 0){
            $("#warn1").text("不能为空");
            flag_name = false;
        }
        var $txtShort = $("#txt-short").val();
        if($txtShort.length== 0){
            $("#warn2").text("不能为空");
            flag_short = false;
        }
        if(flag_name&&flag_short) {
        	var params = {
            		'app_id':$("#wj_app_id").val(),
            		'page_name':$("#txt-name").val(),
            		'page_code':$("#txt-short").val()
            	};
        	var data=null;
        	$.ajax({
        		type: 'post',
        		url: host +'/app.do?method=addNewBlankPage',
        		cache: false,
        		async: false,
        		data: params,
        		dataType: 'json',
        		success: function (returndata) {
        			if ("0" != returndata.code) {
        				alert(returndata.msg);
        				return;
        			}
        			data = returndata.data;
        			refreshPagesPulldown(data.pages);
        		},
        		error: function(){
        			alert("请求出错，新建微景展页面失败！");
        			return;
        		}
        	});

        	$('li.current').removeClass('current');
        	$('#layermain').html("");
            $('#layermain').css("background-color","#ffffff");  
        	var item = $('<li class="drop-item current"></li>')
            var content = $('<div class="mod"><img src="' + host +'/img/sample.png" alt="缩略图"'
            		+ 'onclick="getPageData('
            		+ '\''+ data.page_id + '\','
            		+ '\''+ data.page_code + '\','
            		+ '\''+ data.page_name + '\',this);">'

            		+ '<div class="fun-page"><a href="#" class="modify"'
            		+ ' onclick="modifyPageName('
            		+ '\''+ data.page_id + '\','
            		+ '\''+ data.page_code + '\','
            		+ '\''+ data.page_name + '\');">'
            		+ '编辑'
            		+ '</a>'
            		+ '<a href="#" class="delete"'
            		+ ' onclick="deletePage('
            		+ '\''+ data.page_id + '\');">'
            		+ '删除 '+'</a></div>');
        	item.append(content);
            $("#list-page").append(item);
            $overlay.css("display","none");
            $("#pop-add").css("display","none");
            $('#wj_page_name').val($txtName);
            $('#wj_page_code').val($txtShort);
            $('#wj_page_id').val(data.page_id);
                 
            $('#layermain').attr("component-type","bgc");
            $('#layermain').attr("component-id","bgc"+new Date().getTime()+Math.floor(Math.random()*10));
            // 创建新微景页的时候，同时保存
            
        }
    }

    //编辑页面确定按钮
    function modifyItem(){
        var flag_name = true,
        	flag_short = true,
        	$txtName = $("#txt-name-modify").val();
        if($txtName.length == 0){
            $("#warn3").text("不能为空");
            flag_name = false;
        }
        var $txtShort = $("#txt-short-modify").val();
        if($txtShort.length== 0){
            $("#warn4").text("不能为空");
            flag_short = false;
        }
        if(flag_name&&flag_short) {
        	var params = {
            		'app_id':$("#wj_app_id").val(),
            		'page_id':$("#modify_page_id").val(),
            		'page_name':$("#txt-name-modify").val(),
            		'page_code':$("#txt-short-modify").val()
            	};
        	$.ajax({
        		type: 'post',
        		url: host +'/app.do?method=modifyPageName',
        		cache: false,
        		async: false,
        		data: params,
        		dataType: 'json',
        		success: function (returndata) {
        			if ("0" != returndata.code) {
        				alert(returndata.msg);
        				return;
        			}
        			refreshPagesPulldown(returndata.data.pages);
        		},
        		error: function(){
        			alert("请求出错，名称变更失败！");
        			return;
        		}
        	});
        	$overlay.css("display","none");
            $("#pop-edit").css("display","none");
            $('#wj_page_name').val($txtName);
            $('#wj_page_code').val($txtShort);
        }
    }
    //检测中文名称是否为空,新建窗口
    function verifyName(){
        var $txtName = $("#txt-name").val();
        if($txtName.length == 0){
            $("#warn1").text("不能为空");
        }else{
            $("#warn1").text("");
        }
    }
    //检测英文简称是否为空，新建窗口
    function verifyAbbr(){
        var $txtShort = $("#txt-short").val();
        if($txtShort.length== 0) {
            $("#warn2").text("不能为空");
        }else{
            $("#warn2").text("");
        }
    }
    //检测中文名称是否为空,编辑窗口
    function modifyName(){
        var $txtName = $("#txt-name-modify").val();
        if($txtName.length == 0){
            $("#warn3").text("不能为空");
        }else{
            $("#warn3").text("");
        }
    }
    //检测英文简称是否为空，编辑窗口
    function modifyAbbr(){
        var $txtShort = $("#txt-short-modify").val();
        if($txtShort.length == 0) {
            $("#warn4").text("不能为空");
        }else{
            $("#warn4").text("");
        }
    }
    //删除微景展缩略图
    function delCata(ev){
        var delItem = $(ev.target).parent().parent().parent();
        $overlay.css("display","block");
        var $pop_window = $("#pop-delete");
        var h = $pop_window.height();
        var w = $pop_window.width();
        var $height = $(window).height();
        var $width = $(window).width();
        $pop_window.css({
            "display":"block",
            "top":($height-h)/2,
            "left":($width-w)/2
        });
        $("#btn-verify1").click(function(){
        	var params = {
            		'app_id':$("#wj_app_id").val(),
            		'page_id':$("#delete_page_id").val()
            	};
        	$.ajax({
        		type: 'post',
        		url: host +'/app.do?method=deletePage',
        		cache: false,
        		async: false,
        		data: params,
        		dataType: 'json',
        		success: function (returndata) {
        			$overlay.css("display","none");
                    $("div.pop").css("display","none");
        			if ("0" != returndata.code) {
        				alert(returndata.msg);
        				return;
        			}
        			if(delItem.hasClass('current')){
        				delItem.prev().addClass("current");
        			}
        			delItem.remove();
        			refreshPagesPulldown(returndata.data.pages);
        		},
        		error: function(){
        			 $overlay.css("display","none");
                     $("div.pop").css("display","none");
        			alert("请求出错，删除失败！");
        			return;
        		}
        	});
        });
    }
    //保存功能
    function save(){
        //$(".save").text("不能为空");
    	var jsonstr = htmltoJson();
    	var params = {
    		'src_page':jsonstr
    	};
    	$.ajax({
    		type: 'post',
    		url: host +'/app.do?method=save_one_page',
    		cache: false,
    		async: false,
    		data: params,
    		dataType: 'json',
    		success: function (returndata) {
    			alert(returndata.msg);
    		},
    		error: function(){
    			alert("请求出错，保存失败！");
    			return;
    		}
    	});
    }
    //    二维码预览
    function previewQR(){
    	var wj_app_id = $('#wj_app_id').val();
    	var params = {
    		'app_id':wj_app_id
    	};
        $.ajax({
        	type: 'post',
    		url: host +'/app.do?method=preview',
    		cache: false,
    		async: false,
    		data: params,
    		dataType: 'json',
            success: function (returndata) {
                if ('0' == returndata.code) {
                	$("#QR-show").css("display","block");
                    $("#QRimg").attr("src", returndata.data.index);
                } else  {
                	$("#QR-show").css("display","none");
                	alert(returndata.msg);
                }
            },
            error: function (returndata) {
                alert("失败");
            }
        });
    }
    
    /*
     * 页面的分享【设置】按钮被点击后的事件
     */
    //页面级属性设计
    function setUp(){
    	var wj_app_id = $('#wj_app_id').val();
    	var params = {
    		'app_id':wj_app_id
    	};
        $.ajax({
        	// 获取现有的APP信息以及分享设置信息
	        url: host + "/app.do?method=getSettingOfApp",
	        type: 'POST',
	        async: false,
	        data: params,//发送到后台的数据
	        dataType:"json",
	        success: function (returndata) {
	        	if ("0" == returndata.code) {

		    		$("#wj-page-title").val(returndata.data.app_name);//返回页面的标题
		    		$("#wj-page-description").val(returndata.data.app_note);
		    		$("#wj-page").attr("src", returndata.data.app_thumb);

		    		$("#wj-share").attr("src", returndata.data.share_info_pic);
		    		$("#wj-share-title").val(returndata.data.share_info_title);
		    		$("#wj-share-description").val(returndata.data.share_info_des);
	        	} else {
	        		alert(returndata.msg);
	        		return;
	        	}
	        },
	        error: function (returndata) {
	            alert("请求失败");
	            return;
	        }
	    });

        $overlay.css("display","block");
        var $pop_window = $("#pop-set");
        var h = $pop_window.height();
        var w = $pop_window.width();
        var $height = $(window).height();
        var $width = $(window).width();
        $pop_window.css({
            "display":"block",
            "top":($height-h)/2,
            "left":($width-w)/2
        });
    }
});

function modifyPageName(page_id, page_code, page_name) {
	$('#modify_page_id').val(page_id);
	$('#txt-name-modify').val(page_name);
	$('#txt-short-modify').val(page_code);
};

function deletePage(page_id) {
	$('#delete_page_id').val(page_id);
};
//function getPageData(page_id, page_code, page_name,obj) {
//	$target_selected = $(obj).parent().parent();
//	$target_selected.siblings().removeClass("current");
//	$target_selected.addClass("current");
//	$('#layermain').html("");
//	$('#layermain').css("background-color","#ffffff");
//	var params = {
//			'page_id':page_id
//	}
//	var attr = '';
//	var data = '';
//
//	if (page_id == '' ) {
//		return;
//	}
//	$.ajax({
//		type: 'post',
//		url: host +'/app.do?method=getAllAttrsOfShowPage',
//		cache: false,
//		async: false,
//		data: params,
//		dataType: 'json',
//		success: function (returndata) {
//			if ("0" == returndata.code) {
//				attr = returndata;
//			}
//		},
//		error: function() {
//			alert("请求出错，保存失败！");
//		}
//	});
//
//	$.ajax({
//		type: 'post',
//		url: host +'/app.do?method=getAllDatasOfShowPage',
//		cache: false,
//		async: false,
//		data: params,
//		dataType: 'json',
//		success: function (returndata) {
//			if ("0" == returndata.code) {
//				data = returndata;
//			}
//		},
//		error: function() {
//			alert("请求出错，保存失败！");
//		}
//	});
//
//	if (attr == '' || data == '') {
//		alert("属性或者数据有错误！");
//		return;
//	}
//	jsontoHtml(data, attr);
//	changetobg();
//	$('#wj_page_id').val(page_id);
//	$('#wj_page_name').val(page_name);
//	$('#wj_page_code').val(page_code);
//};


$(document).ready(function(){
	var page_id = $("#wj_page_id").val();
	var page_code =$("#wj_page_code").val();
	var page_name =$("#wj_page_name").val();
	getPageData(page_id, page_code, page_name,"#first-abbr");
});



function refreshPagesPulldown(pages) {
	var pulldown = $("#selectedValue");
	pulldown.empty();
	for (var i = 0; i < pages.length; i++) {
		var item = pages[i];
		pulldown.append("<option value = '"+item.page_id+"'>"+item.page_name+"</option>");
	};
};


$("button").click(function(){
  $("#button2").trigger("click");
});
