package ms.luna.biz.dao;

import ms.luna.biz.dao.model.MsArticle;
import ms.luna.biz.dao.model.MsArticleCriteria;
import ms.luna.biz.dao.model.MsArticleWithBLOBs;

import java.util.List;

public interface MsArticleDAOBase {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int countByCriteria(MsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int deleteByCriteria(MsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    Integer insert(MsArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    Integer insertSelective(MsArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    List<MsArticleWithBLOBs> selectByCriteriaWithBLOBs(MsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    List<MsArticle> selectByCriteriaWithoutBLOBs(MsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    MsArticleWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int updateByCriteriaSelective(MsArticleWithBLOBs record, MsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int updateByCriteria(MsArticleWithBLOBs record, MsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int updateByCriteria(MsArticle record, MsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int updateByPrimaryKeySelective(MsArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int updateByPrimaryKey(MsArticleWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ms_article
     *
     * @mbggenerated Tue Jul 12 17:41:53 CST 2016
     */
    int updateByPrimaryKey(MsArticle record);
}